---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: fedora-21
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

# http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
# http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box
# http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box